/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gptc
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newdonor_btn = new javax.swing.JMenuItem();
        update_btn = new javax.swing.JMenuItem();
        fulldetials_btn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        loc_btn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        delete_donor = new javax.swing.JMenuItem();
        logout_btn = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, 290));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("DONATE BLOOD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 220, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("SAVE LIFE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 130, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Donor.png"))); // NOI18N
        jMenu1.setText("DONER");

        newdonor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add new.png"))); // NOI18N
        newdonor_btn.setText("ADD DONER");
        newdonor_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newdonor_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newdonor_btnMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newdonor_btnMousePressed(evt);
            }
        });
        newdonor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newdonor_btnActionPerformed(evt);
            }
        });
        jMenu1.add(newdonor_btn);

        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update details.png"))); // NOI18N
        update_btn.setText("UPDATE DONER");
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                update_btnMousePressed(evt);
            }
        });
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jMenu1.add(update_btn);

        fulldetials_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Details.png"))); // NOI18N
        fulldetials_btn.setText("ALL DONERS");
        fulldetials_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fulldetials_btnMousePressed(evt);
            }
        });
        fulldetials_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulldetials_btnActionPerformed(evt);
            }
        });
        jMenu1.add(fulldetials_btn);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search user.png"))); // NOI18N
        jMenu2.setText("SEARCH");

        loc_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Location.png"))); // NOI18N
        loc_btn.setText("LOCATION AND BLOOD");
        loc_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loc_btnMousePressed(evt);
            }
        });
        loc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_btnActionPerformed(evt);
            }
        });
        jMenu2.add(loc_btn);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete donor.png"))); // NOI18N
        jMenu4.setText("DELETE");

        delete_donor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        delete_donor.setText("DELETE DONER");
        delete_donor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delete_donorMousePressed(evt);
            }
        });
        jMenu4.add(delete_donor);

        jMenuBar1.add(jMenu4);

        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        logout_btn.setText("LOGOUT");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout_btnMousePressed(evt);
            }
        });
        jMenuBar1.add(logout_btn);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jMenu5.setText("EXIT");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fulldetials_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulldetials_btnActionPerformed
        // TODO add your handling code here:
        adminview f=new adminview();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fulldetials_btnActionPerformed

    private void newdonor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newdonor_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newdonor_btnActionPerformed

    private void loc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_btnActionPerformed
        // TODO add your handling code here:
        adminsearch f=new adminsearch();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loc_btnActionPerformed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
             System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MousePressed

    private void newdonor_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newdonor_btnMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_newdonor_btnMouseEntered

    private void newdonor_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newdonor_btnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newdonor_btnMouseClicked

    private void newdonor_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newdonor_btnMousePressed
        // TODO add your handling code here:
        admindonor s=new admindonor();
        s.setVisible(true);
      
    }//GEN-LAST:event_newdonor_btnMousePressed

    private void update_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMousePressed
        // TODO add your handling code here:
        adminupdate s=new adminupdate();
        s.setVisible(true);
        
    }//GEN-LAST:event_update_btnMousePressed

    private void loc_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loc_btnMousePressed
        // TODO add your handling code here:
        location s=new location();
        s.setVisible(true);
        
    }//GEN-LAST:event_loc_btnMousePressed

    private void delete_donorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_donorMousePressed
        // TODO add your handling code here:
        deletedonor s=new deletedonor();
         s.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_delete_donorMousePressed

    private void fulldetials_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fulldetials_btnMousePressed
        // TODO add your handling code here:
         adminview s=new adminview();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fulldetials_btnMousePressed

    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
        // TODO add your handling code here:
        login s=new login();
        s.setVisible(true);
    }//GEN-LAST:event_logout_btnMousePressed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem delete_donor;
    private javax.swing.JMenuItem fulldetials_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loc_btn;
    private javax.swing.JMenu logout_btn;
    private javax.swing.JMenuItem newdonor_btn;
    private javax.swing.JMenuItem update_btn;
    // End of variables declaration//GEN-END:variables
}
